global using System.Net;
global using System.Net.Http.Json;
global using System.Text.Json;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc.Testing;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using MyWebApp.Controllers;
global using MyWebApp.Services;